# Generated by Django 4.0.4 on 2022-05-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('apartmentNum', models.IntegerField()),
                ('zipCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BagModel',
            fields=[
                ('storeId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField()),
                ('branch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField()),
                ('bags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.bagmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('storeId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTransactionModel',
            fields=[
                ('storeId', models.IntegerField()),
                ('storeName', models.CharField(max_length=100)),
                ('transactionId', models.IntegerField(primary_key=True, serialize=False)),
                ('payemntId', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('products', models.ManyToManyField(to='ModelsBackend.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionModel',
            fields=[
                ('userID', models.UUIDField()),
                ('transactionId', models.IntegerField(primary_key=True, serialize=False)),
                ('paymentId', models.IntegerField()),
                ('date', models.DateField()),
                ('totalAmount', models.IntegerField()),
                ('storeTransactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.storetransactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.cartmodel')),
                ('transactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.usertransactionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bagmodel',
            name='products',
            field=models.ManyToManyField(to='ModelsBackend.productmodel'),
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('member_username', models.CharField(max_length=100)),
                ('member_password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.addressmodel')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.bankmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('ModelsBackend.usermodel',),
        ),
    ]
