# Generated by Django 4.0.4 on 2022-05-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('storeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.addressmodel')),
                ('bankAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.bagmodel')),
                ('founderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.membermodel')),
                ('managers', models.ManyToManyField(related_name='managers', to='ModelsBackend.membermodel')),
                ('owners', models.ManyToManyField(related_name='owners', to='ModelsBackend.membermodel')),
                ('transactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.storetransactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StoreUserPermissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointManager', models.BooleanField()),
                ('appointOwner', models.BooleanField()),
                ('closeStore', models.BooleanField()),
                ('stockManagement', models.BooleanField()),
                ('changePermission', models.BooleanField()),
                ('rolesInformation', models.BooleanField()),
                ('purchaseHistoryInformation', models.BooleanField()),
                ('discount', models.BooleanField()),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.storemodel')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.membermodel')),
            ],
        ),
    ]
