# Generated by Django 4.0.4 on 2022-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0002_storemodel_storeuserpermissionsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='bankAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.bankmodel'),
        ),
    ]
