# Generated by Django 4.0.4 on 2022-05-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0003_alter_storemodel_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductQuantityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.productmodel')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.storemodel')),
            ],
        ),
    ]
