# Generated by Django 4.0.4 on 2022-05-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0004_storeproductquantitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='appointManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='appointOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='changePermission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='closeStore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='purchaseHistoryInformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='rolesInformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='stockManagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.membermodel', unique=True),
        ),
        migrations.CreateModel(
            name='StoreAppointersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigner', models.ManyToManyField(related_name='assigner', to='ModelsBackend.membermodel')),
                ('assingee', models.ManyToManyField(related_name='assingee', to='ModelsBackend.membermodel')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.storemodel')),
            ],
        ),
    ]
