# Generated by Django 4.0.4 on 2022-05-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0005_alter_storeuserpermissionsmodel_appointmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuserpermissionsmodel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsBackend.membermodel'),
        ),
    ]
