# Generated by Django 4.0.4 on 2022-05-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0006_alter_storeuserpermissionsmodel_userid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeuserpermissionsmodel',
            unique_together={('userID', 'storeID')},
        ),
    ]
