# Generated by Django 4.0.4 on 2022-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsBackend', '0008_discountmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='discountID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
